package com.example.leetcodetrainer.adaptive.domain;
import jakarta.persistence.*;
import java.time.Instant;
import java.util.UUID;
@Entity @Table(name="learning_task_attempt")
public class LearningTaskAttempt {
 @Id private UUID id; @Column(name="task_template_id",nullable=false) private UUID taskTemplateId; @Column(name="attempt_id",nullable=false,unique=true) private UUID attemptId; @Column(name="source_attempt_id") private UUID sourceAttemptId; @Column(name="previous_attempt_id") private UUID previousAttemptId; @Enumerated(EnumType.STRING) @Column(nullable=false) private LearningTaskAttemptStatus status; @Column(name="current_checkpoint",nullable=false) private int currentCheckpoint; @Lob private String functionContract,baseCase,subproblems,compositionRule; @Column(nullable=false) private Instant createdAt,lastUpdatedAt; private Instant completedAt;
 protected LearningTaskAttempt(){} public LearningTaskAttempt(UUID id,UUID taskTemplateId,UUID attemptId,Instant now){this(id,taskTemplateId,attemptId,null,null,now);} public LearningTaskAttempt(UUID id,UUID taskTemplateId,UUID attemptId,UUID sourceAttemptId,UUID previousAttemptId,Instant now){this.id=id;this.taskTemplateId=taskTemplateId;this.attemptId=attemptId;this.sourceAttemptId=sourceAttemptId;this.previousAttemptId=previousAttemptId;this.status=LearningTaskAttemptStatus.IN_PROGRESS;this.currentCheckpoint=1;this.createdAt=now;this.lastUpdatedAt=now;}
 public void saveContract(String f,String b,String s,String c,Instant now){if(status!=LearningTaskAttemptStatus.IN_PROGRESS)throw new IllegalStateException("完了済み課題は編集できません。");functionContract=f;baseCase=b;subproblems=s;compositionRule=c;lastUpdatedAt=now;} public void complete(Instant now){if(status==LearningTaskAttemptStatus.COMPLETED)return;if(blank(functionContract)&&blank(baseCase)&&blank(subproblems)&&blank(compositionRule))throw new IllegalStateException("少なくとも1項目を保存してください。");finish(now);} public void completeFourLineContract(Instant now){if(status==LearningTaskAttemptStatus.COMPLETED)return;if(blank(functionContract)||blank(baseCase)||blank(subproblems)||blank(compositionRule))throw new IllegalStateException("Four-line Contractの4項目をすべて保存してください。");finish(now);} private void finish(Instant now){status=LearningTaskAttemptStatus.COMPLETED;completedAt=now;lastUpdatedAt=now;} private boolean blank(String s){return s==null||s.isBlank();}
 public UUID getId(){return id;} public UUID getTaskTemplateId(){return taskTemplateId;} public UUID getAttemptId(){return attemptId;} public UUID getSourceAttemptId(){return sourceAttemptId;} public UUID getPreviousAttemptId(){return previousAttemptId;} public LearningTaskAttemptStatus getStatus(){return status;} public Instant getCompletedAt(){return completedAt;} public String getFunctionContract(){return functionContract;} public String getBaseCase(){return baseCase;} public String getSubproblems(){return subproblems;} public String getCompositionRule(){return compositionRule;}
}
