package com.example.leetcodetrainer.adaptive.domain;
public enum LearningTaskType { KNOWN_RECONSTRUCTION, MICRO_SKILL_DRILL, ISOMORPHIC_TRANSFER, NEAR_TRANSFER, CONTRAST_DISCRIMINATION, DELAYED_RETENTION, COLD_SOLVE, ERROR_REPAIR }
