package com.example.leetcodetrainer.implementation.domain;
public enum ImplementationStatus { NOT_STARTED, IN_PROGRESS, COMPILES_BUT_UNVERIFIED, FAILED_BASIC_CASE, FAILED_EDGE_CASE, RUNTIME_ERROR, CORRECT_AFTER_SELF_DEBUG, CORRECT_AFTER_HINT, CORRECT_AFTER_SOLUTION, CORRECT_FIRST_PASS, ABANDONED }
