const Components = (() => {
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const date = value => value ? new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric'}).format(new Date(`${value}T12:00:00`)) : '—';
  const badge = value => `<span class="badge ${String(value||'NOT_STARTED').toLowerCase().replaceAll('_','-')}">${esc(value||'NOT STARTED')}</span>`;
  const pageHeader=(title,description,action='')=>`<header class="page-header"><div><h1>${esc(title)}</h1>${description?`<p>${esc(description)}</p>`:''}</div>${action}</header>`;
  const empty = message => `<div class="empty"><p>${esc(message)}</p></div>`;
  const progress=(label,value)=>`<div class="progress-line"><div><span>${esc(label)}</span><strong>${value}%</strong></div><progress value="${value}" max="100">${value}%</progress></div>`;
  const domainProgress=(name,completed,total)=>{const value=total?Math.round(completed/total*100):0;return `<section class="domain-progress panel"><div><strong>${esc(name)} Progress</strong><span>${completed} / ${total} interview-ready</span></div>${progress(name,value)}</section>`};
  const resultButtons=id=>`<div class="result-buttons" aria-label="Record result"><button data-action="result" data-id="${id}" data-result="PASS">Answered independently</button><button data-action="result" data-id="${id}" data-result="PARTIAL">Partially answered</button><button data-action="result" data-id="${id}" data-result="FAIL">Could not answer</button></div>`;
  function questionRows(items) { if(!items.length)return empty('No questions yet. Add one to start practising.'); return `<div class="question-list">${items.map(item=>{const java=item.domain==='JAVA_THEORY';return `<article class="question-row" id="question-${item.id}"><div class="question-summary"><button class="question-toggle" data-action="toggle-question" data-id="${item.id}" aria-expanded="false" aria-controls="answer-${item.id}"><span class="question-title">${esc(item.question||item.title)}</span><span class="question-category">${esc(item.category||'')}</span></button><div>${badge(item.latestResult)}</div><div><small>Last</small>${date(item.lastPractisedAt)}</div><div><small>Review</small>${date(item.nextReviewAt)}</div><div class="row-actions"><button class="icon-button" data-action="edit-question" data-id="${item.id}" aria-label="Edit question">✎</button>${!java?`<button data-action="edit-question" data-id="${item.id}">Edit</button>`:''}<button data-action="delete-question" data-id="${item.id}">Delete</button></div></div><section id="answer-${item.id}" class="question-detail" hidden><h3>Prepared answer ${java?`<button class="icon-button" data-action="edit-question-field" data-id="${item.id}" data-field="modelAnswer" aria-label="Edit prepared answer">✎</button>`:''}</h3><p>${esc(item.modelAnswer)}</p><h3>Personal answer & notes ${java?`<button class="icon-button" data-action="edit-question-field" data-id="${item.id}" data-field="personalAnswer" aria-label="Edit personal answer and notes">✎</button>`:''}</h3><p>${esc(item.personalAnswer||item.notes||'No notes yet.')}</p>${java?`<button class="follow-up-toggle" data-action="toggle-follow-ups" data-id="${item.id}" aria-expanded="false" aria-controls="follow-up-${item.id}">Show follow-up questions</button><section id="follow-up-${item.id}" class="follow-up-panel" hidden><h3>Follow-up questions</h3><p>${esc(item.followUps||'—')}</p></section>`:`<><h3>Follow-up questions</h3><p>${esc(item.followUps||'—')}</p></>`}${item.story?`<p><strong>STAR story:</strong> ${esc(item.story)}</p>`:''}<h3>Attempt history</h3>${attemptHistory(App.state.attempts.filter(a=>a.itemId===item.id))}${resultButtons(item.id)}</section></article>`}).join('')}</div>`; }
  function attemptHistory(attempts){return attempts.length?`<div class="attempt-history">${attempts.slice().reverse().map(a=>`<div>${date(a.attemptedAt||a.date)} · ${badge(a.result)}${a.durationMinutes||a.duration?` · ${a.durationMinutes||a.duration} min`:''}${a.notes?` — ${esc(a.notes)}`:''}</div>`).join('')}</div>`:'<p class="muted">No attempts recorded.</p>';}
  function modal(title, body){const dialog=document.getElementById('modal');document.getElementById('modal-content').innerHTML=`<header class="modal-header"><h2 id="modal-title">${esc(title)}</h2><button data-action="close-modal" aria-label="Close dialog">×</button></header>${body}`;dialog.showModal();const first=dialog.querySelector('input,textarea,select,button');first?.focus();}
  const formField=(name,label,value='',type='text',required=false)=> type==='textarea'?`<label>${label}<textarea name="${name}" ${required?'required':''}>${esc(value)}</textarea></label>`:`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''}></label>`;
  return {esc,date,badge,pageHeader,empty,progress,domainProgress,resultButtons,questionRows,attemptHistory,modal,formField};
})();
