package com.example.leetcodetrainer.curriculum.domain;
public enum LearningMode { COLD_DIAGNOSTIC, PROBLEM_COMPREHENSION_REPAIR, BRUTE_FORCE_BUILDER, OPTIMIZATION_DERIVATION, GUIDED_RECONSTRUCTION, IMPLEMENTATION_DIAGNOSTIC, IMPLEMENTATION_REPAIR, CLEAN_REIMPLEMENTATION, RETENTION_REVIEW, ISOMORPHIC_TRANSFER, PATTERN_DISCRIMINATION, TIMED_COLD_SOLVE }
