package com.example.leetcodetrainer.adaptive.service;
import com.example.leetcodetrainer.adaptive.domain.*; import com.example.leetcodetrainer.adaptive.repository.*; import com.example.leetcodetrainer.attempt.domain.*; import com.example.leetcodetrainer.attempt.repository.StageAssessmentRepository; import com.example.leetcodetrainer.attempt.service.AttemptService; import com.example.leetcodetrainer.problem.repository.ProblemRepository; import java.time.Instant; import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @Transactional public class AdaptiveLearningService implements NextTaskSelector {
 private final LearningTaskTemplateRepository tasks; private final LearningTaskAttemptRepository taskAttempts; private final ProblemRepository problems; private final AttemptService attempts; private final StageAssessmentRepository stages; private final ReasoningProfileService profiles;
 public AdaptiveLearningService(LearningTaskTemplateRepository t,LearningTaskAttemptRepository a,ProblemRepository p,AttemptService s,StageAssessmentRepository g,ReasoningProfileService r){tasks=t;taskAttempts=a;problems=p;attempts=s;stages=g;profiles=r;}
 public LearningTaskAttempt start(String code,UUID source){var task=tasks.findByCodeAndActiveTrue(code).orElseThrow(()->new IllegalArgumentException("学習課題が見つかりません。"));if(source!=null){var open=taskAttempts.findFirstByTaskTemplateIdAndSourceAttemptIdAndStatus(task.getId(),source,LearningTaskAttemptStatus.IN_PROGRESS);if(open.isPresent())return open.get();}return create(task,source,null);} public LearningTaskAttempt retry(UUID previousId){var previous=taskAttempt(previousId);if(previous.getStatus()!=LearningTaskAttemptStatus.COMPLETED)throw new IllegalStateException("完了済み課題だけを再試行できます。");return create(tasks.findById(previous.getTaskTemplateId()).orElseThrow(),previous.getSourceAttemptId(),previous.getId());} private LearningTaskAttempt create(LearningTaskTemplate task,UUID source,UUID previous){var problem=problems.findBySlug(task.getSourceProblemSlug()).orElseThrow();var attempt=attempts.start(problem.getId(),AttemptType.CURRICULUM_TASK);return taskAttempts.save(new LearningTaskAttempt(UUID.randomUUID(),task.getId(),attempt.getId(),source,previous,Instant.now()));}
 public void completeTask(UUID id){var attempt=taskAttempt(id);var template=tasks.findById(attempt.getTaskTemplateId()).orElseThrow();if("maximum-depth-four-line-contract".equals(template.getCode()))attempt.completeFourLineContract(Instant.now());else attempt.complete(Instant.now());}
 @Transactional(readOnly=true) public LearningTaskAttempt taskAttempt(UUID id){return taskAttempts.findById(id).orElseThrow(()->new IllegalArgumentException("課題記録が見つかりません。"));} @Transactional(readOnly=true) public Optional<LearningTaskTemplate> taskForAttempt(UUID id){return taskAttempts.findByAttemptId(id).flatMap(a->tasks.findById(a.getTaskTemplateId()));}
 public AttemptLearningEvidence evidenceFor(Attempt a){String slug=problems.findById(a.getProblemId()).orElseThrow().getSlug();Map<MicroSkill,MicroSkillEvidence> skills=new EnumMap<>(MicroSkill.class);for(var s:stages.findByAttemptIdOrderByStageTypeAsc(a.getId())){MicroSkill k=s.getStageType()==StageType.PROBLEM_RELATION?MicroSkill.RELATION_ABSTRACTION:s.getStageType()==StageType.REQUIRED_OPERATIONS?MicroSkill.COMPOSITION_RULE:null;if(k!=null)skills.put(k,new MicroSkillEvidence(k,s.getStageOutcome(),s.getAssistanceSource(),null,s.getAnswer()!=null&&!s.getAnswer().isBlank(),0));}return new AttemptLearningEvidence(a.getId(),slug,profiles.profileForSlug(slug),a.getPriorExposure(),a.getFinalResult(),skills,false,false,false);}
 public Optional<NextLearningTask> select(AttemptLearningEvidence e){var relation=e.microSkills().get(MicroSkill.RELATION_ABSTRACTION);if(e.profile()==ReasoningProfileType.LOOKUP_STATE&&e.finalResult()==FinalResult.SOLVED_INDEPENDENTLY&&(e.priorExposure()==PriorExposure.SOLVED_BEFORE||e.priorExposure()==PriorExposure.MEMORISED)&&weak(relation))return Optional.of(task("two-sum-relation-first"));var composition=e.microSkills().get(MicroSkill.COMPOSITION_RULE);if(e.profile()==ReasoningProfileType.RECURSIVE_DIVIDE_AND_COMBINE&&weak(composition))return Optional.of(task("maximum-depth-error-repair"));return Optional.empty();} public Optional<LearningTaskCard> cardFor(Attempt source){return select(evidenceFor(source)).map(initial->{var template=tasks.findByCodeAndActiveTrue(initial.templateId()).orElseThrow();var latest=taskAttempts.findFirstByTaskTemplateIdAndSourceAttemptIdOrderByLastUpdatedAtDesc(template.getId(),source.getId());if(latest.isPresent()&&latest.get().getStatus()==LearningTaskAttemptStatus.COMPLETED){var next=nextTask(template.getCode());if(next!=null){var nextTemplate=tasks.findByCodeAndActiveTrue(next).orElseThrow();return taskAttempts.findFirstByTaskTemplateIdAndSourceAttemptIdOrderByLastUpdatedAtDesc(nextTemplate.getId(),source.getId()).map(a->new LearningTaskCard(task(next),a.getStatus(),a.getId())).orElse(new LearningTaskCard(task(next),LearningTaskAttemptStatus.NOT_STARTED,null));}}return latest.map(a->new LearningTaskCard(initial,a.getStatus(),a.getId())).orElse(new LearningTaskCard(initial,LearningTaskAttemptStatus.NOT_STARTED,null));});} private String nextTask(String code){return switch(code){case "two-sum-relation-first"->"movie-ticket-pair";case "maximum-depth-error-repair"->"count-nodes-transfer";case "count-nodes-transfer"->"minimum-depth-near-transfer";default->null;};} private NextLearningTask task(String code){var t=tasks.findByCodeAndActiveTrue(code).orElseThrow();return new NextLearningTask(t.getCode(),t.getTaskType(),t.getTitle(),t.getPrompt(),t.getSuccessCriteria(),Set.of());} private boolean weak(MicroSkillEvidence e){return e!=null&&(e.outcome()==StageOutcome.PARTIAL||e.outcome()==StageOutcome.BLOCKED);}
}
