package com.example.leetcodetrainer.failure.domain;

public enum FailureLabelCode {
    PROBLEM_STATEMENT_PARSING, RELATION_ABSTRACTION, INPUT_OUTPUT_MODELLING, EXAMPLE_TRACING, BRUTE_FORCE_CONSTRUCTION,
    COMPLEXITY_ANALYSIS, REPEATED_WORK_IDENTIFICATION, UNRESOLVED_STATE_IDENTIFICATION, RESOLUTION_EVENT_IDENTIFICATION,
    UPDATED_REGION_IDENTIFICATION, REQUIRED_OPERATION_DERIVATION, DATA_STRUCTURE_SELECTION, INVARIANT_FORMULATION,
    CORRECTNESS_REASONING, PATTERN_RECOGNITION, PATTERN_DISCRIMINATION, IMPLEMENTATION_TRANSLATION, LANGUAGE_SYNTAX,
    EDGE_CASE_IDENTIFICATION, DEBUGGING, RECALL, TRANSFER, TIME_PRESSURE, EXPLANATION, OTHER
}
