package com.example.leetcodetrainer.implementation.service;
import com.example.leetcodetrainer.attempt.domain.*; import com.example.leetcodetrainer.attempt.service.AttemptService; import com.example.leetcodetrainer.implementation.domain.*; import com.example.leetcodetrainer.implementation.repository.*; import java.time.*; import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @Transactional public class ImplementationReliabilityService { private final ImplementationRecordRepository records; private final ImplementationErrorRepository errors; private final AttemptService attempts; private final Clock clock;
 public ImplementationReliabilityService(ImplementationRecordRepository r,ImplementationErrorRepository e,AttemptService a,Clock c){records=r;errors=e;attempts=a;clock=c;}
 public ImplementationRecord save(UUID attemptId,ImplementationStatus status,boolean compiled,boolean basic,boolean edge,boolean completed,boolean self,boolean hint,int compile,int wrong,int runtime,int timeout,String notes){Attempt a=attempts.get(attemptId); var stage=attempts.stage(attemptId,StageType.IMPLEMENTATION); var record=records.findByAttemptId(attemptId).orElseGet(()->records.save(new ImplementationRecord(UUID.randomUUID(),attemptId,stage.getId(),a.getLanguage(),Instant.now(clock)))); record.save(status,compiled,basic,edge,completed,self,hint,compile,wrong,runtime,timeout,notes,Instant.now(clock)); return record;}
 public ImplementationError addError(UUID attemptId,ImplementationErrorType type,ErrorSource source,ErrorSeverity severity,String input,String expected,String actual,String root,String correction,String prevention){ImplementationRecord r=records.findByAttemptId(attemptId).orElseThrow(()->new IllegalStateException("先に実装記録を保存してください。")); UUID recurrence=errors.findRecentByErrorType(type).stream().filter(e->!e.getId().equals(r.getId())).map(ImplementationError::getId).findFirst().orElse(null); return errors.save(new ImplementationError(UUID.randomUUID(),r.getId(),type,source,severity,input,expected,actual,root,correction,prevention,recurrence,Instant.now(clock)));}
 @Transactional(readOnly=true) public List<ImplementationError> errors(UUID attemptId){return records.findByAttemptId(attemptId).map(r->errors.findByImplementationRecordId(r.getId())).orElse(List.of());}
 @Transactional(readOnly=true) public ImplementationRecord record(UUID attemptId){return records.findByAttemptId(attemptId).orElse(null);}
}
