ALTER TABLE learning_task_attempt ADD COLUMN source_attempt_id UUID;
ALTER TABLE learning_task_attempt ADD COLUMN previous_attempt_id UUID;
ALTER TABLE learning_task_attempt ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS';
ALTER TABLE learning_task_attempt ADD COLUMN current_checkpoint INTEGER NOT NULL DEFAULT 1;
ALTER TABLE learning_task_attempt ADD COLUMN function_contract CLOB;
ALTER TABLE learning_task_attempt ADD COLUMN base_case CLOB;
ALTER TABLE learning_task_attempt ADD COLUMN subproblems CLOB;
ALTER TABLE learning_task_attempt ADD COLUMN composition_rule CLOB;
ALTER TABLE learning_task_attempt ADD COLUMN last_updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE learning_task_attempt ADD COLUMN completed_at TIMESTAMP WITH TIME ZONE;
CREATE INDEX idx_task_attempt_resume ON learning_task_attempt(task_template_id,source_attempt_id,status);
